version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: codekeydb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  plantuml:
    image: plantuml/plantuml-server:jetty
    restart: always
    ports:
      - '8081:8080'
